### ISSUE TITLE
User Auth For Review

### ISSUE THREAD

**Issue by Lijun-Gan** [Lijun-Gan/Amazen#7]
Hey, my user Auth is ready for review !!

**Comment by danemauland** [comment]
# Splash
## Header
Background color is off
Height is off
Don't use images for the elements in the navbar. Add the text and style it yourself. See Font Awesome for icons you can use.
When the webpage is expanded/shrunk, the search bar should be expanding/contracting, not the padding around the other elements.
Remove border between search bar text input and the yellow part containing the search icon
Add border mouseover effect when mousing over the links

## nav bar
I would recommend keeping the spacing between the links the same an what Amazon has, but centering the element containing the links
Add border mouseover effect when mousing over the links
change "recommendation" to "Recommendations"
change "Primes" to "Prime"
Only include links here that you are going to use for a future mvp--remove the others, or replace with links to your LinkedIn/github

# Sign In/Sign Up
Great work here!
Don't use dashes to create the horizontal line here--you can do much better than that
The error message font size is a little too small
Use an icon instead of the "!"
Add the same click effects to "Demo User Sign In" that you have for "Continue"
Don't use a screenshot of their error messages--style your own.

# After signing in
The "Hello, Amazen" gets cut off. It's fine for names to get cut off at some point if they're really long, but it should be able to handle names longer than this without getting cut off

**Comment by Lijun-Gan** [comment]
Thank you so much ! Finished all correction based on your feedback.

**Comment by danemauland** [comment]
Hey Lijun! This looks great. Just a couple finishing touches:

Add hover effects to buttons on sign in/sign up pages (looks like Amazon buttons get slightly darker when hovering)
Remove "or mobile phone number" from sign in page

**Comment by Lijun-Gan** [comment]
Done. Thank you for pointing out!
